# Generated by Django 4.1.13 on 2024-07-04 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_exchange_tradedetail_symbol_alter_trade_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_name', models.CharField(max_length=50)),
                ('exchange_code', models.CharField(max_length=10)),
                ('symbol_id', models.CharField(max_length=20)),
                ('base_currency', models.CharField(max_length=10)),
                ('quote_currency', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('size', models.DecimalField(decimal_places=8, max_digits=20)),
                ('taker_side', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'unique_together': {('exchange_code', 'symbol_id', 'timestamp')},
            },
        ),
        migrations.RemoveField(
            model_name='symbol',
            name='exchange',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='symbol',
        ),
        migrations.RemoveField(
            model_name='tradedetail',
            name='trade',
        ),
        migrations.DeleteModel(
            name='Exchange',
        ),
        migrations.DeleteModel(
            name='Symbol',
        ),
        migrations.DeleteModel(
            name='Trade',
        ),
        migrations.DeleteModel(
            name='TradeDetail',
        ),
    ]
