# Generated by Django 4.1.13 on 2024-07-04 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_exchange_symbol_trade_tradedetail_delete_marketdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symbol',
            name='exchange',
        ),
        migrations.RemoveField(
            model_name='tradedetail',
            name='trade',
        ),
        migrations.AlterField(
            model_name='trade',
            name='symbol',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='Exchange',
        ),
        migrations.DeleteModel(
            name='Symbol',
        ),
        migrations.DeleteModel(
            name='TradeDetail',
        ),
    ]
